apiVersion: apps/v1
kind: Deployment
metadata:
    name: f35-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: f35-deployment
    template:
        metadata:
            labels:
                app: f35-deployment
        spec:
            containers:
                - name: f35-container-a
                  image: ${ECR_REGISTRY}/${CONTAINER_A}:${SEMAPHORE_WORKFLOW_ID}
                  args: ["localhost", "9991", "32 32 32"]
                  imagePullPolicy: Always
                - name: f35-container-b
                  image: ${ECR_REGISTRY}/${CONTAINER_B}:${SEMAPHORE_WORKFLOW_ID}
                  args: ["-vl", "8888"]
                  imagePullPolicy: Always
                - name: f35-dexter-upload
                  image: ${ECR_REGISTRY}/${CONTAINER_DEX}:${SEMAPHORE_WORKFLOW_ID}
                  imagePullPolicy: Always
            imagePullSecrets:
                - name: aws-ecr
